### ISSUE TITLE
Year 2017+ Header doesn't parse

### ISSUE THREAD

**Issue by cecil-t** [zero-motorcycle-community/zero-log-parser#11]
The header section of the MBB files don't parse properly on 2017 (and presumably newer) VINs.  The data in the file seems to parse ok but the header looks like this:

"
Zero MBB log

Serial number      ZtWR  ]   sj421
VIN                20:12            
Firmware rev.      1536
Board rev.         125
Model              W

Printing 3925 of 3925 log entries..

 Entry    Time of Log            Event                      Conditions
+--------+----------------------+--------------------------+----------------------------------
"

( none of the fields above show proper data - Serial number through Model

**Comment by adaviel** [comment]
python-2.6.6 on CentOS 6, 2017 Zero FXS

./zero_log_parser.py 538XXBZ48HCJ08346_MBB_2017-11-04.bin
Traceback (most recent call last):
  File "./zero_log_parser.py", line 839, in <module>
    parse_log(log_file, output_file)
  File "./zero_log_parser.py", line 736, in parse_log
    print('Parsing {}...'.format(bin_file))
ValueError: zero length field name in format


I note that my VIN is at offset 0x252 and bike model at 0x26c

I don't know Python well enough to debug; I'm better at Perl

[538XXBZ48HCJ08346_MBB_2017-11-04.zip](https://github.com/zero-motorcycle-community/zero-log-parser/files/1473646/538XXBZ48HCJ08346_MBB_2017-11-04.zip)

**Comment by shaleh** [comment]
Does any one have a 2016 log file? It looks like the format was extended. There is a zeroed out chunk where the current code is looking for the VIN. As @adaviel points out, the VIN is at 0x252, not 0x240 as the current code expects.

**Comment by cecil-t** [comment]
Here's a few sample logs of older files that should parse properly.

[Zero-14-15-16-sample-logs.zip](https://github.com/zero-motorcycle-community/zero-log-parser/files/1775389/Zero-14-15-16-sample-logs.zip)

**Comment by cecil-t** [comment]
And a few more 2017 samples
[Zero-17-sample-logs.zip](https://github.com/zero-motorcycle-community/zero-log-parser/files/1775423/Zero-17-sample-logs.zip)

**Comment by shaleh** [comment]
2018 samples?

**Comment by shaleh** [comment]
My suspicion is the firmware revision changed and the log file parser needs to track the firmware version of the file.

**Comment by cecil-t** [comment]
I'll double check but haven't seen any 2018 VINs yet.

I don't think it's related to firmware version.  My 2014, vin 03455 in the zip file above, has the latest firmware but still parses fine.

You'll also notice that in 2015 or 2016 the .bin file sizes doubled from 128k to 256k.  So there are definitely differences in the years beyond firmware.

**Comment by tyzbit** [comment]
Here are some logs from a 2018 SR.
[Zero-18-sample-log.zip](https://github.com/zero-motorcycle-community/zero-log-parser/files/3100647/Zero-18-sample-log.zip)

**Comment by glynnelson** [comment]
Here are a 2019 DSR logs, the original converted and the way I manually modify the header so I can correctly parse the data in Keith Thomas' Google Sheets Visual Zero Log spreadsheet.

[logs.zip](https://github.com/zero-motorcycle-community/zero-log-parser/files/4236512/logs.zip)

**Comment by briantrice** [comment]
I forgot about this issue, sorry. I did receive a 2019 log which I managed to parse reasonably well, but without an official decoding from Zero, I had to guess.

Please try the latest log parser on these logs. I'll take time to re-test it myself now as well but might be delayed.

**Comment by briantrice** [comment]
Revised to handle firmware revision and model better:
https://github.com/zero-motorcycle-community/zero-log-parser/commit/d0eddf5a1351b83f597f9100f1c664181062c6df

**Comment by 6ffm70** [comment]
I have a similar issue with a 2022 FXE MBB log (reproduced with two of two different samples):
```
Zero Unknown Type log

VIN                
Model              
Initial date        Change Does Not Req
System info        unknown

Printing 7094 of 7094 log entries..
```
The BMS headers repeat as follows (looks ok to me):
```
Zero BMS log

Initial date       Jul 13 2022 10:28:45
Pack serial number 19lb3***

Printing 7582 of 7582 log entries..
```

Output test.py:
```
======================================================================
FAIL: test_can_handle_logs_in_dir (__main__.TestLogParserDirectory) (log_name='538XXFZA2NCM18***_MBB_2022-08-12.bin', dir='')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 144, in test_can_handle_logs_in_dir
    self._test_parse_of_logfile(log_file)
  File "test.py", line 104, in _test_parse_of_logfile
    self.fail(msg=log_record.message)
AssertionError: Unknown Log Format

======================================================================
FAIL: test_can_handle_logs_in_dir (__main__.TestLogParserDirectory) (log_name='538XXFZA2NCM18***_MBB_2022-11-11.bin', dir='')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 144, in test_can_handle_logs_in_dir
    self._test_parse_of_logfile(log_file)
  File "test.py", line 104, in _test_parse_of_logfile
    self.fail(msg=log_record.message)
AssertionError: Unknown Log Format

----------------------------------------------------------------------
Ran 2 tests in 0.785s
```
There's a third a third MBB*.bin in that directory where no FAIL was reported. Tested this, output seems ok except from _Model_ and _Initial date_ (model=FXE, logfile date is from 2022-08-25; bike was produced 2021-07):
```
Zero MBB log

Serial number      RKT212300***
VIN                538XXFZA2NCM18***
Firmware rev.      33
Board rev.         3236
Model              FX
Initial date       Apr 13 2021 07:20:53

Printing 7026 of 7026 log entries..
```
